/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { useEffect, useState } from "react"

const Home: NextPage = () => {
  const [isFlagEnabled, setIsFlagEnabled] = useState(false)
  // get isFlagEnabled
  useEffect(() => {
    setIsFlagEnabled(
      Boolean(
        typeof localStorage !== "undefined" &&
          localStorage.getItem("isFlagEnabled") === "true",
      ),
    )
  }, [])
  return (
    <div className="flex min-h-screen max-w-full overflow-hidden bg-black text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-4 mt-4">
        <div className="flex flex-col font-bold">
          <Link href="/lists">Lists →</Link>

          <Link href="/settings">Settings →</Link>
        </div>

        <div
          // hoverしたらスクロールバーを表示するscrollbarを追加
          className="hidden-scrollbar scrollbar grid w-screen auto-cols-max grid-flow-col gap-0 overflow-scroll"
        ></div>

        {isFlagEnabled && <p>isFlagEnabled is Enabled</p>}
        {!isFlagEnabled && <p>isFlagEnabled is Disabled</p>}
      </main>
    </div>
  )
}

export default Home
