name: Take screenshot and update README

on:
  push:
    branches:
      - feature/alpha

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Take screenshot
        run: node scripts/take-screenshot.js

      - name: Upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png

      - name: Install search-replace-action
        uses: jacobtomlinson/search-replace-action@v1.2.0

      - name: Replace screenshot
        run: |
          sed -i.bak 's/<!-- screenshot -->/![screenshot](https:\/\/github.com\/<YOUR_USERNAME>\/<YOUR_REPOSITORY>\/raw\/feature\/alpha\/screenshot.png)/g' README.md

      - name: Commit screenshot
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: Add screenshot
          add: README.md

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CASTRA_TOKEN }}
