name: Take screenshot and update README

on:
  push:
    branches: [main]

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Take screenshot
        run: node scripts/take-screenshot.js

      - name: Commit screenshot
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: Add screenshot
          add: README.md

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          CASTRA_TOKEN: ${{ secrets.CASTRA_TOKEN }}
