name: Take screenshot and update README

on:
  push:
    branches:
      - feature/alpha

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Take screenshot
        run: node scripts/take-screenshot.js

      - name: Upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png

      - name: Replace screenshot
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.CASTRA_TOKEN }}
          owner: Coordinate-Cat
          repo: castra
          filename: README.md
          search: "<!-- screenshot -->"
          replace: "![screenshot](https://github.com/Coordinate-Cat/castra/raw/feature/alpha/screenshot.png)"
